[package]
name = "labrpc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4.18", features = ["derive"] }
log = "0.4"
futures = "0.3"
opentelemetry = { version = "0.21.0" }
opentelemetry-jaeger = { version = "0.20.0", features = ["rt-tokio"] }
rand = "0.8"
tarpc = { version = "0.34", features = ["full"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
tracing = { version = "0.1" }
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
opentelemetry_sdk = "0.21.2"
async-trait = "0.1.80"
bincode = "1.3.3"
serde = { version = "1.0.203", features = ["derive"] }

[lib]
name = "service"
path = "src/lib.rs"
